### ISSUE TITLE
Review February 15

### ISSUE THREAD

**Issue by iamciera** [cabinetofcuriosity/paleobiology_DB_explore#3]
## Part 1 - Dinosaurs

Shaping up nicely. I really love how you can just follow the link and everything is downloaded to the computer!  I wish every database offered this option.

- [x] Add a bit more on why you were initially interested in this database.
- [x] Can you link to the documentation on the what the columns mean?
- [x] It might be a good idea to look at the species here. A lot of these cannot be Dinosuars.
 I added a bit more to the reasoning here: 
>"Jurassic Park" should have been called "Cretaceous Park"! Dinosaurs lived during the Mesozoic, which is composed of three persiods: Triassic, Jurrassic then the Cretaceous. Maybe there are more fossils during the Cretaceous because it was closer in time to now? Antother question - why the Paleogene and Neogene are present, since dinosaurs did not live during this time? AND why are there so many fossils found in the Quaternary period from 2,588,000 years ago till now. What species are in these time periods?
- [x] One way to quickly explore the species represented in the time period would be to combine these two bar graphs.  Making era be a color in the period bar graph or making  the opposite. Or making 
<img width="701" alt="screen shot 2019-02-15 at 11 01 40 am" src="https://user-images.githubusercontent.com/1732390/52878343-37b00b80-3111-11e9-8a56-77a80e3c82ad.png">

<img width="714" alt="screen shot 2019-02-15 at 11 00 18 am" src="https://user-images.githubusercontent.com/1732390/52878249-03d4e600-3111-11e9-8459-e1685c88fd1b.png"> 

- [x] Check out [facet_grid](https://seaborn.pydata.org/generated/seaborn.FacetGrid.html)
